import { Inter, Mulish } from "next/font/google";
import "./globals.css";
// import Header from "./components/header";
import Headerr from "./components/Header";
import { Roboto } from 'next/font/google'
import Footer from "./components/Footer";
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"className={roboto.className}>
      <body className={inter.className}>
        {/* <Header /> */}
        <Headerr/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
